name: Releases

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.22' # The Go version to download (if necessary) and use.
      - uses: actions/checkout@v4
      - run:
          make package-all
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "packages/*"
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: up9cloud/action-notify@master
        if: cancelled() == false
        env:
          GITHUB_JOB_STATUS: ${{ job.status }}
          TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_BOT_TOKEN}}
          TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}
