FROM alpine:3.7

ENV GOCRON_AGENT_VERSION=v1.6.2

RUN apk add --no-cache ca-certificates  tzdata bash \
    &&  mkdir -p /app \
    &&  wget -P /tmp  https://github.com/up9cloud/gocron2/releases/download/${GOCRON_AGENT_VERSION}/gocron2-node-${GOCRON_AGENT_VERSION}-linux-amd64.tar.gz \
    &&  cd /tmp \
    &&  tar  zvxf gocron2-node-${GOCRON_AGENT_VERSION}-linux-amd64.tar.gz  \
    &&  mv /tmp/gocron2-node-linux-amd64/gocron2-node /app \
    &&  rm  -rf /tmp/*

WORKDIR /app
EXPOSE 5921

ENTRYPOINT ["/app/gocron2-node", "-allow-root"]
