FROM alpine:3.7

ENV GOCRON2_NODE_VERSION=v1.6.2

WORKDIR /app
RUN set -ex; \
    apk add --no-cache \
        ca-certificates \
        tzdata \
        bash \
        ; \
    wget -P /tmp https://github.com/up9cloud/gocron2/releases/download/${GOCRON2_NODE_VERSION}/gocron2-node-${GOCRON2_NODE_VERSION}-linux-amd64.tar.gz; \
    cd /tmp; \
    tar zvxf gocron2-node-${GOCRON2_NODE_VERSION}-linux-amd64.tar.gz; \
    mv /tmp/gocron2-node /app; \
    rm -rf /tmp/*

EXPOSE 5921
ENTRYPOINT ["/app/gocron2-node", "-allow-root"]
