apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: gocron2-agent
  namespace: kube-system
spec:
  selector:
    matchLabels:
      daemon: gocron2-agent
  template:
    metadata:
      labels:
        daemon: gocron2-agent
      name: gocron2-agent
    spec:
      containers:
      - name: gocron2-agent
        image: crontab-agent:0.5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5921
          hostPort: 5921
          name: gocron2-agent
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/log
          name: syslog
      hostNetwork: true
      hostPID: true
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /var/log
          type: Directory
        name: syslog